version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  lockbot:
    lang: python3-flask-debian
    handler: ./lockbot
    image: martindekov/lockbot:0.0.1
    environment:
      github_repository: push2
      inactive_days: 90
      exec_timeout: 30s
      read_timeout: 30s
      write_timeout: 30s
    secrets:
      - auth-token
    annotations:
      topic: cron-function
      schedule: "*/1 * * * *"